name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Criar o arquivo ZIP ignorando o diretório .github/
      - name: Create ZIP file, excluding .github/
        run: |
          zip -r project.zip . -x ".github/*"

      # Fazer o upload do ZIP como artefato
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-artifact
          path: project.zip
